module.exports = {
  defaultServerResponse: {
    status: 400,
    message: "",
    body: {},
  },
  statisticsMessage: {
    STATISTICS_CREATED: "Statistic Created",
    STATISTICS_FETCHED: "Statistic Fetched",
    STATISTICS_UPDATED: "Statistic Updated",
    STATISTICS_NOT_FOUND: "Statistic Not Found",
    STATISTICS_DELETED: "Statistic Deleted",
  },
  jobMessage: {
    JOB_CREATED: "Job Created",
    JOB_FETCHED: "Job Fetched",
    JOB_UPDATED: "Job Updated",
    JOB_NOT_FOUND: "Job Not Found",
    JOB_DELETED: "Job Deleted",
  },
  SettingsMessage: {
    SETTING_CREATED: "Setting Created",
    SETTING_FETCHED: "Setting Fetched",
    SETTING_UPDATED: "Setting Updated",
    SETTING_NOT_FOUND: "Setting Not Found",
    SETTING_DELETED: "Setting Deleted",
  },
  contactMessage: {
    CONTACT_CREATED: "Contact Created",
    CONTACT_FETCHED: "Contact Fetched",
    CONTACT_UPDATED: "Contact Updated",
    CONTACT_NOT_FOUND: "Contact Not Found",
    CONTACT_DELETED: "Contact Deleted",
  },
  commentMessage: {
    COMMENT_CREATED: "Comment Created",
    COMMENT_FETCHED: "Comment Fetched",
    COMMENT_UPDATED: "Comment Updated",
    COMMENT_NOT_FOUND: "Comment Not Found",
    COMMENT_DELETED: "Comment Deleted",
  },
  sliderMessage: {
    SLIDER_CREATED: "Slider Created",
    SLIDER_FETCHED: "Slider Fetched",
    SLIDER_UPDATED: "Slider Updated",
    SLIDER_NOT_FOUND: "Slider Not Found",
    SLIDER_DELETED: "Slider Deleted",
  },
  customerMessage: {
    CUSTOMER_CREATED: "Customer Created",
    CUSTOMER_FETCHED: "Customer Fetched",
    CUSTOMER_UPDATED: "Customer Updated",
    CUSTOMER_NOT_FOUND: "Customer Not Found",
    CUSTOMER_DELETED: "Customer Deleted",
  },
  aboutMessage: {
    ABOUT_CREATED: "About Created",
    ABOUT_FETCHED: "About Fetched",
    ABOUT_UPDATED: "About Updated",
    ABOUT_NOT_FOUND: "About Not Found",
    ABOUT_DELETED: "About Deleted",
  },
  serviceMessage: {
    SERVICE_CREATED: "Service Created",
    SERVICE_FETCHED: "Service Fetched",
    SERVICE_UPDATED: "Service Updated",
    SERVICE_NOT_FOUND: "Service Not Found",
    SERVICE_DELETED: "Service Deleted",
  },
  requestMessage: {
    REQUEST_CREATED: "Request Created",
    REQUEST_FETCHED: "Request Fetched",
    REQUEST_UPDATED: "Request Updated",
    REQUEST_NOT_FOUND: "Request Not Found",
    REQUEST_DELETED: "Request Deleted",
  },
  jobRequestMessage: {
    JOB_REQUEST_CREATED: "JobRequest Created",
    JOB_REQUEST_FETCHED: "JobRequest Fetched",
    JOB_REQUEST_UPDATED: "JobRequest Updated",
    JOB_REQUEST_NOT_FOUND: "JobRequest Not Found",
    JOB_REQUEST_DELETED: "JobRequest Deleted",
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created",
    PRODUCT_FETCHED: "Product Fetched",
    PRODUCT_UPDATED: "Product Updated",
    PRODUCT_NOT_FOUND: "Product Not Found",
    PRODUCT_DELETED: "Product Deleted",
  },
  adminMessage: {
    SIGNUP_SUCCESS: "Signup Success",
    LOGIN_SUCCESS: "Login Success",
    USER_FETCHED: "User Fetched",
    USER_NOT_FOUND: "User Not Found",
    INVALID_PASSWORD: "Incorrect Password",
    DUPLICATE_EMAIL: "User already exist with given email",
  },
  requestValidationMessage: {
    INVALID_FIELDS: "Invalid Fields",
    TOKEN_MISSING: "Token missing from header",
  },
  databaseMessages: {
    INVALID_ID: "Invalid Id",
  },
};
